apiVersion: v1
kind: ConfigMap
metadata:
  name: test-backstage
  namespace: arch
  labels:
    'backstage.io/kubernetes-id': test-backstage
data:
  foo: bar
---
apiVersion: v1
kind: Service
metadata:
  name: test-backstage
  namespace: arch
  labels:
    'backstage.io/kubernetes-id': test-backstage
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: test-backstage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backstage
  namespace: arch
  labels:
    'backstage.io/kubernetes-id': test-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backstage
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-backstage
        'backstage.io/kubernetes-id': test-backstage
    spec:
      containers:
      - name: backend
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
